---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url:
sections:
- type: heading
  label: Blog
- type: directory
  path: content/english/blog
  label: Posts (en)
  create: documents
  match: "*.md"
  templates:
  - post
- type: directory
  path: content/french/blog
  label: Posts (fr)
  create: documents
  match: "*.md"
  templates:
  - post
- type: heading
  label: Authors
- type: directory
  path: content/english/author
  label: Authors (en)
  create: documents
  match: "**/*"
  templates:
  - author
- type: directory
  path: content/french/author
  label: Authors (fr)
  create: documents
  match: "*.md"
  templates:
  - author
- type: heading
  label: Data
- type: directory
  path: data
  label: Homepage
  create: all
  match: "*.yml"
- type: directory
  path: i18n
  label: i18n
  create: documents
  match: ".yaml"
- type: heading
  label: Configuration
- type: document
  path: config.toml
  label: Config
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.75.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
